/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooGenPdfPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooGenPdfPdf); 

 RooGenPdfPdf::RooGenPdfPdf(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _alpha) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   alpha("alpha","alpha",this,_alpha)
 { 
 } 


 RooGenPdfPdf::RooGenPdfPdf(const RooGenPdfPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   alpha("alpha",this,other.alpha)
 { 
 } 



 Double_t RooGenPdfPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return (1+0.1*fabs(x)+sin(sqrt(fabs(x*alpha+0.1)))) ; 
 } 



